"""empty message

Revision ID: 110245a7a600
Revises: 87ef4d152f6e
Create Date: 2022-04-02 17:10:38.181622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110245a7a600'
down_revision = '87ef4d152f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
