"""empty message

Revision ID: 1e4f14f01a0e
Revises: 5f8108450484
Create Date: 2022-03-09 23:29:13.272725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4f14f01a0e'
down_revision = '5f8108450484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('price_id', 'prices', ['price_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('price_id', type_='foreignkey')
        batch_op.drop_column('price_id')

    # ### end Alembic commands ###
