"""empty message

Revision ID: 7e4a1cb1bb21
Revises: 110245a7a600
Create Date: 2022-05-01 13:28:40.084099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4a1cb1bb21'
down_revision = '110245a7a600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.drop_constraint('price_id', type_='foreignkey')
        batch_op.drop_column('price_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('price_id', 'prices', ['price_id'], ['id'])
        batch_op.drop_column('duration')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
